/*
 * Yoast.com provisioning API
 * The Yoast provisioning API
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.68
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import ProductVersionDto from './ProductVersionDto';

/**
 * The ProductVersionsDto model module.
 * @module model/ProductVersionsDto
 * @version 1.0.0
 */
export default class ProductVersionsDto {
  /**
   * Constructs a new <code>ProductVersionsDto</code>.
   * @alias module:model/ProductVersionsDto
   * @class
   * @param versions {Array.<module:model/ProductVersionDto>} 
   */
  constructor(versions) {
    this.versions = versions;
  }

  /**
   * Constructs a <code>ProductVersionsDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ProductVersionsDto} obj Optional instance to populate.
   * @return {module:model/ProductVersionsDto} The populated <code>ProductVersionsDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ProductVersionsDto();
      if (data.hasOwnProperty('versions'))
        obj.versions = ApiClient.convertToType(data['versions'], [ProductVersionDto]);
    }
    return obj;
  }
}

/**
 * @member {Array.<module:model/ProductVersionDto>} versions
 */
ProductVersionsDto.prototype.versions = undefined;

