/*
 * Yoast.com provisioning API
 * The Yoast provisioning API
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.68
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The ProductVersionDto model module.
 * @module model/ProductVersionDto
 * @version 1.0.0
 */
export default class ProductVersionDto {
  /**
   * Constructs a new <code>ProductVersionDto</code>.
   * @alias module:model/ProductVersionDto
   * @class
   * @param name {String} 
   * @param slug {String} 
   * @param version {String} 
   * @param downloadUrl {String} 
   */
  constructor(name, slug, version, downloadUrl) {
    this.name = name;
    this.slug = slug;
    this.version = version;
    this.downloadUrl = downloadUrl;
  }

  /**
   * Constructs a <code>ProductVersionDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ProductVersionDto} obj Optional instance to populate.
   * @return {module:model/ProductVersionDto} The populated <code>ProductVersionDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ProductVersionDto();
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('slug'))
        obj.slug = ApiClient.convertToType(data['slug'], 'String');
      if (data.hasOwnProperty('version'))
        obj.version = ApiClient.convertToType(data['version'], 'String');
      if (data.hasOwnProperty('downloadUrl'))
        obj.downloadUrl = ApiClient.convertToType(data['downloadUrl'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} name
 */
ProductVersionDto.prototype.name = undefined;

/**
 * @member {String} slug
 */
ProductVersionDto.prototype.slug = undefined;

/**
 * @member {String} version
 */
ProductVersionDto.prototype.version = undefined;

/**
 * @member {String} downloadUrl
 */
ProductVersionDto.prototype.downloadUrl = undefined;

