/*
 * Yoast.com provisioning API
 * The Yoast provisioning API
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.68
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.YoastProvisionerApiClient);
  }
}(this, function(expect, YoastProvisionerApiClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new YoastProvisionerApiClient.SubscriptionProvisioningApi();
  });

  describe('(package)', function() {
    describe('SubscriptionProvisioningApi', function() {
      describe('subscriptionProvisioningControllerCancelSubscription', function() {
        it('should call subscriptionProvisioningControllerCancelSubscription successfully', function(done) {
          // TODO: uncomment, update parameter values for subscriptionProvisioningControllerCancelSubscription call and complete the assertions
          /*

          instance.subscriptionProvisioningControllerCancelSubscription(body, id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(YoastProvisionerApiClient.SubscriptionProvisioningResponseDto);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('subscriptionProvisioningControllerCreate', function() {
        it('should call subscriptionProvisioningControllerCreate successfully', function(done) {
          // TODO: uncomment, update parameter values for subscriptionProvisioningControllerCreate call and complete the assertions
          /*

          instance.subscriptionProvisioningControllerCreate(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(YoastProvisionerApiClient.SubscriptionProvisioningResponseDto);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('subscriptionProvisioningControllerGetOne', function() {
        it('should call subscriptionProvisioningControllerGetOne successfully', function(done) {
          // TODO: uncomment, update parameter values for subscriptionProvisioningControllerGetOne call and complete the assertions
          /*

          instance.subscriptionProvisioningControllerGetOne(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(YoastProvisionerApiClient.SubscriptionProvisioningResponseDto);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('subscriptionProvisioningControllerRefundSubscription', function() {
        it('should call subscriptionProvisioningControllerRefundSubscription successfully', function(done) {
          // TODO: uncomment, update parameter values for subscriptionProvisioningControllerRefundSubscription call and complete the assertions
          /*

          instance.subscriptionProvisioningControllerRefundSubscription(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(YoastProvisionerApiClient.SubscriptionProvisioningResponseDto);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('subscriptionProvisioningControllerRenewSubscription', function() {
        it('should call subscriptionProvisioningControllerRenewSubscription successfully', function(done) {
          // TODO: uncomment, update parameter values for subscriptionProvisioningControllerRenewSubscription call and complete the assertions
          /*

          instance.subscriptionProvisioningControllerRenewSubscription(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(YoastProvisionerApiClient.SubscriptionProvisioningResponseDto);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('subscriptionProvisioningControllerSetSiteForSubscription', function() {
        it('should call subscriptionProvisioningControllerSetSiteForSubscription successfully', function(done) {
          // TODO: uncomment, update parameter values for subscriptionProvisioningControllerSetSiteForSubscription call and complete the assertions
          /*

          instance.subscriptionProvisioningControllerSetSiteForSubscription(body, id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(YoastProvisionerApiClient.SubscriptionProvisioningResponseDto);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
